# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2013, Numenta, Inc.  Unless you have an agreement
# with Numenta, Inc., for a separate license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------


## This file defines parameters for a prediction experiment.

###############################################################################
#                                IMPORTANT!!!
# This params file is dynamically generated by the RunExperimentPermutations
# script. Any changes made manually will be over-written the next time
# RunExperimentPermutations is run!!!
###############################################################################


from nupic.frameworks.opf.exp_description_helpers import importBaseDescription

# the sub-experiment configuration
config ={
  'aggregationInfo' : {'seconds': 0, 'fields': [], 'months': 0, 'days': 0, 'years': 0, 'hours': 0, 'microseconds': 0, 'weeks': 0, 'minutes': 0, 'milliseconds': 0},
  'modelParams' : {'tmParams': {'minThreshold': 10, 'activationThreshold': 12, 'pamLength': 1}, 'sensorParams': {'encoders': {'_classifierInput': {'maxval': 98, 'classifierOnly': True, 'minval': 1, 'clipInput': True, 'n': 85, 'fieldname': 'faelle', 'w': 21, 'type': 'ScalarEncoder'}, u'wstday_weekend': {'name': 'wstday', 'type': 'DateEncoder', 'fieldname': 'wstday', 'weekend': (21, 1)}, u'Influenza': None, u'wstday_timeOfDay': None, u'wstday_dayOfWeek': None, u'faelle': None, u'Grippe': None}}, 'spParams': {'synPermInactiveDec': 0.07889238851891935}, 'clParams': {'alpha': 0.003156105429668137}},

}

mod = importBaseDescription('../description.py', config)
locals().update(mod.__dict__)
